---
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
    name: manager

spec:
    minAvailable: 1
    selector:
        matchLabels:
            app: manager
            version: v1
            platform: foreman
