---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
    name: manager
    namespace: foreman

spec:
    refreshInterval: 1h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: manager
        creationPolicy: Owner
    dataFrom:
        - extract:
              key: /schifferers/foreman/manager/credentials
